declare module "@salesforce/resourceUrl/NGMCP_CWRHowdoyouconfirmthejobisraisedandmonitorviajobnumbercompressed" {
    var NGMCP_CWRHowdoyouconfirmthejobisraisedandmonitorviajobnumbercompressed: string;
    export default NGMCP_CWRHowdoyouconfirmthejobisraisedandmonitorviajobnumbercompressed;
}