declare module "@salesforce/resourceUrl/NGMCP_CWRHowdoyouraiseaworkrequestforRemoveU40withpurgingcompressed" {
    var NGMCP_CWRHowdoyouraiseaworkrequestforRemoveU40withpurgingcompressed: string;
    export default NGMCP_CWRHowdoyouraiseaworkrequestforRemoveU40withpurgingcompressed;
}