declare module "@salesforce/resourceUrl/NGMCP_NSHowdoyouDownloadacceptquotationanduploadthequotationresponsecompressed" {
    var NGMCP_NSHowdoyouDownloadacceptquotationanduploadthequotationresponsecompressed: string;
    export default NGMCP_NSHowdoyouDownloadacceptquotationanduploadthequotationresponsecompressed;
}