/*
** Description: This class is used in FFA**
*/
public with sharing class AuxillaryControl {
    public string AuxillaryControlSerialNumber;
    public string AuxillaryControlManufacturer;
    public string AuxillaryControlModel;
    public string AuxillaryControlYearOfManufacture;
    public date DateInstalled;
    public string PrimaryFunction;
    public string Connectionsize;
    public string Connectiontype;
    public string InstalledOnStream;
    public string PressureRead;
    public AuxillaryControl() {
    }
}