/*
** Description: This class is used in FFA**
*/
public with sharing class AuxillaryRelief {
    public string AuxillaryReliefSerialNumber;
    public string AuxillaryReliefManufacturer;
    public string AuxillaryReliefModel;
    public string AuxillaryReliefYearOfManufacture;
    public date DateInstalled;
    public string PrimaryFunction;
    public string Connectionsize; 
    public string Connectiontype;
    public string InstalledOnStream;
    public string PressureRead;
    public AuxillaryRelief() {
    }
}