/**
* @File Name : CommunityLoginController.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : December 9, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | December 9, 2025 |   | Initial Version
**/

public class CommunityLoginController {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}