/*
** Description: This class is used in FFA**
*/
public class Convertor {
    public string ConvertorSerialNumber;
    public string ConvertorManufacturer;
    public string ConvertorModel;
    public string ConvertorYearOfManufacture;
    public string ConvertorLocationCode;
    public string ConvertorLocationNotes;
    public string ConvertorNumberOfDials;
    public string ConvertorNumberOfUnits;
    public string ConvertorImperialIndicator;
    public string PreviousUnconvertedReading;
    public string PreviousConvertedReading;
    Public string InstalledOnStream;
    public date DateInstalled;
    
    public Convertor (){}
}