/*
** Description: This class is used in FFA**
*/
public with sharing class CreepRelief {
    public string CreepReliefSerialNumber;
    public string CreepReliefManufacturer;
    public string CreepReliefModel;
    public string CreepReliefYearOfManufacture;
    public date DateInstalled;
    public string PrimaryFunction;
    public string PhysicalSize;
    public string PressureRead;
    public string Connectionsize;
    public string Connectiontype;
    public string InstalledOnStream;
    
    public CreepRelief() {
        
    }
}