public with sharing class FFA_Site {
    
        public String Title;
        public String Initials;
        public String Surname;
        public String ContactTelephoneNumber;
        public String SiteName;
        public String BuildingName;
        public String SubBuildingName;
        public String BuildingNumber;
        public String DependentStreet;
        public String PrincipalStreet;
        public String DependentLocality;
        public String DoubleDependantLocality;
        public String PostTown;
        public String County;
        public String PostcodeOutcode;
        public String PostcodeIncode;
        public String GPSEasting;
        public String GPSNorthing;
        public String AccessInstructions;
        public String AccessRestrictions;
        public String PressureTier;
        public String CorrespondenceAddress;
        public String DoesTheSiteContainAsbestos;
        public String AsbestosDetails;
        public string InletPressure;
        public string OutletPressure;
        public string ConversionFactor;
        public string LocationofMpoint;
        //Added New feilds as per I-384802
        public string Type_Of_Vessel;
        public string Vessel_Id;
        public string Pressure_System_Number;
        public string Pressure_System_Name;
        public string Aginame;
        public string CareComment;
        
        public FFA_Site(){}
    
}