/*
** Description: This class is used in FFA**
*/
public class Filters{
    public string FiltersSerialNumber;
    public string FiltersManufacturer;
    public string FiltersModel;
    public string FilterYearOfManufacture;
    public date DateInstalled;
    public string PrimaryFunction;
    public string Physicalsize;
    public string Connectionsize;
    public string Connectiontype;
    public string InstalledOnStream;
    public string PressureRead;
    
    public Filters(){}
}