/*
** Description: This class is used in FFA**
*/
public with sharing class FlowComputer {
    public string FlowComputerSerialNumber;
    public string FlowComputerManufacturer;
    public string FlowComputerModel;
    public string FlowComputerYearOfManufacture;
    public date DateInstalled;
    public string FlowComputerLocationCode;
    public string FlowComputerrImperialIndicator;
    public string FlowComputerNumberOfDials;
    public string PreviousUnconvertedReading;
    public string PreviousConvertedReading;
    public string InstalledOnStream;
    public FlowComputer (){}
}