public class FlowUserRow {
   @InvocableVariable public String action;
   @InvocableVariable public String firstName;
   @InvocableVariable public String lastName;
   @InvocableVariable public String email;
   @InvocableVariable public String role;
   @InvocableVariable public String supplierGroup;
   @InvocableVariable public String supplierCode;
   @InvocableVariable public String userName; // for change / deactivate
}