/*
** Description: This class is used in FFA**
*/
public with sharing class Job{
    public string ServiceProvider;
    public string SiteID;
    public string MeterPointReferenceNumber;
    public string RequestedAppointmentTimeslot;
    public string ShipperID;
    public string ShipperName;
    public string MeterProvider;
    public string ServiceNotificationNumber;
    public string OperationNumber;
    public string JobCode;
    public string JobDescription;
    public string RequestCreatedDate;
    public string RequestCreatedTime;
    public string RequestedAppointmentDate;
    public string RequestedAppointmentEndDate;
    //public string AssetType;
    public string UnplannedPolicyStartDate;
    public string UnplannedPolicyEndDate;
    public string JobNotes;
    public string NewManufacturerName;
    public string NewModelName;
    public string NewMeterManufacturedYear;
    public string NewMeterMechanism;
    public string NewMeterPaymentType;
    public string NewNumberOfDials;
    public string NewImperialMeInd;
    public string NewMeasuringCap;
    public string NatureOfJob;
    public string NotificationType;
    public string ServiceRequestnum;
    public Boolean AMRFlag;
    public Boolean Microbusiness;
    public String FaultReason;
    public String supplierid;
    public job(){}        
}