/*
** Description: This class is used in FFA**
*/
public with sharing class Regulator{
    public string RegulatorFunction;
    public string RegulatorSerialNumber;
    public string RegulatorManufacturer;
    public string RegulatorModel;
    public string RegulatorYearOfManufacture;
    public string RegulatorInstalledOnStream;
    public string RegulatorSetPoint;
    public date DateInstalled;
    public string PrimaryFunction;
    public string PhysicalSize;
    public string PressureRead;
    public string Connectionsize;
    public string Connectiontype;
    public string PressureTier;
}