/*
** Description: This class is used in FFA**
*/
public with sharing class SlamShut{
    public string SlamShutSerialNumber;
    public string SlamShutManufacturer;
    public string SlamShutModel;
    public string SlamShutYearOfManufacture;
    public string DateInstalled;
    public string PrimaryFunction;
    public String PhysicalSize;
    public string PressureRead;
    public string Connectionsize;
    public string Connectiontype;
    public string InstalledOnStream;
    public SlamShut(){}
}