/*
** Description: This class is used in FFA**
*/
public with sharing class Valves{
    public string ValvesSerialNumber;
    public string ValvesManufacturer;
    public string ValvesModel;
    public string ValvesYearOfManufacture;
    public date DateInstalled;
    public string PrimaryFunction;
    public string PhysicalSize;
    public string Connectionsize;
    public string Connectiontype;
    public string InstalledOnStream;
    public valves(){}
}